### ISSUE TITLE
Conditional Rules

### ISSUE THREAD

**Issue by renfrewcountyscanner** [Dom2364/PlaneAlerter#23]
Hi,

Is there a way to do the conditional rules where they are OR's vs ALL for the conditions?

**Comment by Dom2364** [comment]
There isn't a way of doing this at the moment but it shouldn't be too hard to add this in the next update, I'll add it to the list

**Comment by jimsy3** [comment]
what is that?
and could the condition editor have the same exact spec names or smth as the VirtualRadar report? aka VR probably has "S-mode country" as "Registered country" in the editor, so it's a bit hard to find all of the same things/matches...

**Comment by jimsy3** [comment]
PS: maybe add some extra code to make the program display the date and time into the console too, when i press "restart" - and maybe even add an automatic restart at every midnight or 00:01 with the date and time also added into the console text?

**Comment by jimsy3** [comment]
also - maybe make the console text move all of the previous text upwards automatically, so you would always get the most recent alert on the screen, plus maybe even make it move a bit higher from the bottom, so that it doesnt stick to the very bottom, which would make it look a bit too stuck and annoying...

**Comment by Dom2364** [comment]
Added in [2.6.0](https://github.com/Dom2364/PlaneAlerter/releases/tag/2.6.0)
